SHELL = /bin/sh

all: amara
amara:
	cd converters; ./configure; make
	cd amarakosha; ./configure; make

install:
	cd amarakosha; make install
	#cp -pr ../scl_amara/amarakosha ../scl_amara/converters SCLINSTALLDIR

uninstall:
	rm -r SCLINSTALLDIR/amarakosha HTDOCSDIR/amarakosha CGIDIR/amarakosha TFPATH/AMARA_DOT
